/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TelegramSidebarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/constants.ts
var VIEW_TYPE_TELEGRAM = "telegram-sidebar-view";
var TELEGRAM_WEB_K = "https://web.telegram.org/k/";
var TELEGRAM_WEB_A = "https://web.telegram.org/a/";

// src/TelegramView.ts
var import_obsidian = require("obsidian");
var TelegramView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.tabBarEl = null;
    this.webviewContainerEl = null;
    this.webviews = /* @__PURE__ */ new Map();
    this.activeTabId = "default";
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_TELEGRAM;
  }
  getDisplayText() {
    return "Telegram";
  }
  getIcon() {
    return "send";
  }
  async onOpen() {
    this.contentEl.empty();
    this.contentEl.addClass("telegram-sidebar-container");
    this.tabBarEl = this.contentEl.createDiv({ cls: "telegram-sidebar-tab-bar" });
    this.webviewContainerEl = this.contentEl.createDiv({ cls: "telegram-sidebar-webview-container" });
    this.buildTabs();
  }
  async onClose() {
    this.webviews.clear();
    this.tabBarEl = null;
    this.webviewContainerEl = null;
  }
  buildTabs() {
    var _a;
    if (!this.tabBarEl || !this.webviewContainerEl)
      return;
    this.tabBarEl.empty();
    this.webviewContainerEl.empty();
    this.webviews.clear();
    const tabs = [];
    const defaultUsername = this.plugin.settings.telegramUsername;
    tabs.push({
      id: "default",
      name: defaultUsername || "Telegram",
      username: defaultUsername
    });
    this.plugin.settings.botTabs.forEach((bot, i) => {
      if (bot.username) {
        tabs.push({
          id: `tab-${i}`,
          name: bot.name || bot.username,
          username: bot.username
        });
      }
    });
    const hasTabs = tabs.length > 1;
    this.tabBarEl.toggleClass("telegram-sidebar-tab-bar-hidden", !hasTabs);
    tabs.forEach((tab) => {
      const tabBtn = this.tabBarEl.createEl("button", {
        text: tab.name,
        cls: "telegram-sidebar-tab-btn"
      });
      tabBtn.dataset.tabId = tab.id;
      tabBtn.addEventListener("click", () => this.switchTab(tab.id));
      const webviewEl = this.createWebview(tab.username);
      this.webviewContainerEl.appendChild(webviewEl);
      this.webviews.set(tab.id, {
        el: webviewEl,
        username: tab.username,
        name: tab.name
      });
    });
    this.activeTabId = ((_a = tabs[0]) == null ? void 0 : _a.id) || "default";
    this.switchTab(this.activeTabId);
  }
  refreshTabs() {
    this.buildTabs();
  }
  switchTab(tabId) {
    var _a;
    this.activeTabId = tabId;
    this.webviews.forEach((entry, id) => {
      entry.el.toggleClass("telegram-sidebar-webview-active", id === tabId);
      entry.el.toggleClass("telegram-sidebar-webview-hidden", id !== tabId);
    });
    (_a = this.tabBarEl) == null ? void 0 : _a.querySelectorAll(".telegram-sidebar-tab-btn").forEach((btn) => {
      const el = btn;
      el.toggleClass("telegram-sidebar-tab-btn-active", el.dataset.tabId === tabId);
    });
  }
  createWebview(username) {
    const doc = this.contentEl.doc;
    const webviewEl = doc.createElement("webview");
    const url = this.buildUrlForUsername(username);
    webviewEl.setAttribute("src", url);
    webviewEl.setAttribute("allowpopups", "");
    webviewEl.setAttribute("partition", `persist:telegram-sidebar-${this.app.appId}`);
    webviewEl.addClass("telegram-sidebar-webview");
    webviewEl.addEventListener("did-fail-load", (event) => {
      if (event.errorCode !== -3) {
        console.error("Telegram Sidebar: Failed to load", event.errorDescription);
      }
    });
    webviewEl.addEventListener("new-window", (event) => {
      if (event.url) {
        window.open(event.url);
      }
    });
    webviewEl.addEventListener("destroyed", () => {
      if (doc !== this.contentEl.doc) {
        webviewEl.detach();
        this.buildTabs();
      }
    });
    return webviewEl;
  }
  getActiveWebview() {
    const entry = this.webviews.get(this.activeTabId);
    return (entry == null ? void 0 : entry.el) || null;
  }
  buildUrlForUsername(username) {
    const base = this.plugin.settings.webVersion === "a" ? TELEGRAM_WEB_A : TELEGRAM_WEB_K;
    if (!username) {
      return base;
    }
    return `${base}#@${username}`;
  }
  buildUrl() {
    return this.buildUrlForUsername(this.plugin.settings.telegramUsername);
  }
  reload() {
    const webview = this.getActiveWebview();
    if (webview) {
      webview.reload();
    }
  }
  navigateToChat(username) {
    const webview = this.getActiveWebview();
    if (webview) {
      const url = this.buildUrlForUsername(username);
      webview.loadURL(url);
    }
  }
  async insertTextToChat(text) {
    const webview = this.getActiveWebview();
    if (!webview)
      return;
    const escaped = text.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\n/g, "\\n");
    const isVersionA = this.plugin.settings.webVersion === "a";
    const selector = isVersionA ? "#editable-message-text" : ".input-message-input";
    const js = `
			(function() {
				var el = document.querySelector('${selector}');
				if (!el) return false;
				el.focus();
				document.execCommand('insertText', false, '${escaped}');
				el.dispatchEvent(new Event('input', { bubbles: true }));
				return true;
			})();
		`;
    webview.executeJavaScript(js, true);
  }
  async getSelectedText() {
    const webview = this.getActiveWebview();
    if (!webview)
      return "";
    try {
      const text = await webview.executeJavaScript(
        "window.getSelection().toString()",
        true
      );
      return text || "";
    } catch (e) {
      return "";
    }
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  telegramUsername: "",
  webVersion: "k",
  panelSide: "right",
  autoOpen: false,
  botTabs: []
};
var TelegramSidebarSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Telegram Sidebar Settings" });
    new import_obsidian2.Setting(containerEl).setName("Telegram Username").setDesc(
      "Enter the username of the bot, user, or channel to open on launch (without @). Leave empty to show the main Telegram screen."
    ).addText(
      (text) => text.setPlaceholder("e.g. moltbot").setValue(this.plugin.settings.telegramUsername).onChange(async (value) => {
        this.plugin.settings.telegramUsername = value.trim().replace(/^@/, "");
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Telegram Web Version").setDesc("K version is lightweight. A version is React-based with modern UI.").addDropdown(
      (dropdown) => dropdown.addOption("k", "K (Lightweight)").addOption("a", "A (Modern React)").setValue(this.plugin.settings.webVersion).onChange(async (value) => {
        this.plugin.settings.webVersion = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Panel Side").setDesc("Which side of the workspace to open the Telegram panel.").addDropdown(
      (dropdown) => dropdown.addOption("right", "Right").addOption("left", "Left").setValue(this.plugin.settings.panelSide).onChange(async (value) => {
        this.plugin.settings.panelSide = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Auto Open on Startup").setDesc("Automatically open the Telegram sidebar when Obsidian starts.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoOpen).onChange(async (value) => {
        this.plugin.settings.autoOpen = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "Bot Tabs" });
    containerEl.createEl("p", {
      text: "Add multiple bots/chats as tabs. Switch between them in the sidebar.",
      cls: "setting-item-description"
    });
    this.plugin.settings.botTabs.forEach((tab, index) => {
      const s = new import_obsidian2.Setting(containerEl).setName(`Tab ${index + 1}`).addText(
        (text) => text.setPlaceholder("Display name").setValue(tab.name).onChange(async (value) => {
          this.plugin.settings.botTabs[index].name = value;
          await this.plugin.saveSettings();
        })
      ).addText(
        (text) => text.setPlaceholder("username (without @)").setValue(tab.username).onChange(async (value) => {
          this.plugin.settings.botTabs[index].username = value.trim().replace(/^@/, "");
          await this.plugin.saveSettings();
        })
      ).addExtraButton(
        (btn) => btn.setIcon("trash").setTooltip("Remove tab").onClick(async () => {
          this.plugin.settings.botTabs.splice(index, 1);
          await this.plugin.saveSettings();
          this.display();
        })
      );
      s.infoEl.remove();
    });
    new import_obsidian2.Setting(containerEl).addButton(
      (btn) => btn.setButtonText("Add Tab").setCta().onClick(async () => {
        this.plugin.settings.botTabs.push({ name: "", username: "" });
        await this.plugin.saveSettings();
        this.display();
      })
    );
  }
};

// src/main.ts
var TelegramSidebarPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_TELEGRAM, (leaf) => {
      return new TelegramView(leaf, this);
    });
    this.addRibbonIcon("send", "Open Telegram Sidebar", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-telegram-sidebar",
      name: "Open Telegram Sidebar",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "reload-telegram",
      name: "Reload Telegram",
      callback: () => this.reloadView()
    });
    this.addCommand({
      id: "go-to-chat",
      name: "Go to Chat",
      callback: () => {
        const view = this.getActiveView();
        if (view) {
          view.navigateToChat(this.settings.telegramUsername);
        } else {
          this.activateView();
        }
      }
    });
    this.addCommand({
      id: "send-note-path-to-telegram",
      name: "Send Current Note Path to Telegram",
      callback: () => this.sendNotePathToTelegram()
    });
    this.addCommand({
      id: "send-selection-to-telegram",
      name: "Send Selected Text to Telegram",
      editorCallback: (editor) => {
        const selectedText = editor.getSelection();
        if (!selectedText) {
          new import_obsidian3.Notice("No text selected");
          return;
        }
        const view = this.getActiveView();
        if (view) {
          view.insertTextToChat(selectedText);
          new import_obsidian3.Notice("Text sent to Telegram input");
        } else {
          new import_obsidian3.Notice("Telegram sidebar is not open");
        }
      }
    });
    this.addCommand({
      id: "save-telegram-selection-to-note",
      name: "Save Telegram Selection to Note",
      callback: async () => {
        const telegramView = this.getActiveView();
        if (!telegramView) {
          new import_obsidian3.Notice("Telegram sidebar is not open");
          return;
        }
        const selectedText = await telegramView.getSelectedText();
        if (!selectedText) {
          new import_obsidian3.Notice("No text selected in Telegram");
          return;
        }
        const markdownLeaf = this.app.workspace.getLeavesOfType("markdown");
        const activeMarkdownLeaf = markdownLeaf.find(
          (leaf) => leaf.view instanceof import_obsidian3.MarkdownView
        );
        if (!activeMarkdownLeaf) {
          new import_obsidian3.Notice("No active note to save to");
          return;
        }
        const editor = activeMarkdownLeaf.view.editor;
        const cursor = editor.getCursor();
        editor.replaceRange(`
${selectedText}
`, cursor);
        new import_obsidian3.Notice("Telegram text saved to note");
      }
    });
    this.addSettingTab(new TelegramSidebarSettingTab(this.app, this));
    if (this.settings.autoOpen) {
      this.app.workspace.onLayoutReady(() => {
        this.activateView();
      });
    }
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_TELEGRAM);
  }
  async activateView() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_TELEGRAM);
    if (existing.length > 0) {
      workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.settings.panelSide === "left" ? workspace.getLeftLeaf(false) : workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({
        type: VIEW_TYPE_TELEGRAM,
        active: true
      });
      workspace.revealLeaf(leaf);
    }
  }
  getActiveView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_TELEGRAM);
    if (leaves.length > 0) {
      return leaves[0].view;
    }
    return null;
  }
  reloadView() {
    const view = this.getActiveView();
    if (view) {
      view.reload();
    }
  }
  async sendNotePathToTelegram() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile)
      return;
    const vaultBasePath = this.app.vault.adapter.basePath;
    const absolutePath = `${vaultBasePath}/${activeFile.path}`;
    const view = this.getActiveView();
    if (!view) {
      await this.activateView();
      const newView = this.getActiveView();
      if (newView) {
        setTimeout(() => newView.insertTextToChat(absolutePath), 1e3);
      }
      return;
    }
    view.insertTextToChat(absolutePath);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
