/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TelegramSidebarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/constants.ts
var VIEW_TYPE_TELEGRAM = "telegram-sidebar-view";
var TELEGRAM_WEB_K = "https://web.telegram.org/k/";
var TELEGRAM_WEB_A = "https://web.telegram.org/a/";

// src/TelegramView.ts
var import_obsidian = require("obsidian");
var TelegramView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.webviewEl = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_TELEGRAM;
  }
  getDisplayText() {
    return "Telegram";
  }
  getIcon() {
    return "send";
  }
  async onOpen() {
    this.contentEl.empty();
    this.contentEl.addClass("telegram-sidebar-container");
    this.createWebview();
  }
  async onClose() {
    this.webviewEl = null;
  }
  createWebview() {
    const doc = this.contentEl.doc;
    this.webviewEl = doc.createElement("webview");
    this.webviewEl.setAttribute("src", this.buildUrl());
    this.webviewEl.setAttribute("allowpopups", "");
    this.webviewEl.setAttribute("partition", `persist:telegram-sidebar-${this.app.appId}`);
    this.webviewEl.addClass("telegram-sidebar-webview");
    this.webviewEl.addEventListener("did-fail-load", (event) => {
      if (event.errorCode !== -3) {
        console.error("Telegram Sidebar: Failed to load", event.errorDescription);
        this.showError(event.errorDescription);
      }
    });
    this.webviewEl.addEventListener("new-window", (event) => {
      if (event.url) {
        window.open(event.url);
      }
    });
    this.webviewEl.addEventListener("destroyed", () => {
      var _a;
      if (doc !== this.contentEl.doc) {
        (_a = this.webviewEl) == null ? void 0 : _a.detach();
        this.createWebview();
      }
    });
    this.contentEl.appendChild(this.webviewEl);
  }
  buildUrl() {
    const base = this.plugin.settings.webVersion === "a" ? TELEGRAM_WEB_A : TELEGRAM_WEB_K;
    const username = this.plugin.settings.telegramUsername;
    if (!username) {
      return base;
    }
    return `${base}#@${username}`;
  }
  reload() {
    if (this.webviewEl) {
      this.webviewEl.reload();
    }
  }
  navigateToChat(username) {
    if (this.webviewEl) {
      const base = this.plugin.settings.webVersion === "a" ? TELEGRAM_WEB_A : TELEGRAM_WEB_K;
      const url = username ? `${base}#@${username}` : base;
      this.webviewEl.loadURL(url);
    }
  }
  async insertTextToChat(text) {
    if (!this.webviewEl)
      return;
    const escaped = text.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\n/g, "\\n");
    const isVersionA = this.plugin.settings.webVersion === "a";
    const selector = isVersionA ? "#editable-message-text" : ".input-message-input";
    const js = `
			(function() {
				var el = document.querySelector('${selector}');
				if (!el) return false;
				el.focus();
				document.execCommand('insertText', false, '${escaped}');
				el.dispatchEvent(new Event('input', { bubbles: true }));
				return true;
			})();
		`;
    this.webviewEl.executeJavaScript(js, true);
  }
  showError(errorDescription) {
    const errorEl = this.contentEl.createDiv({ cls: "telegram-sidebar-error" });
    errorEl.createEl("h3", { text: "Failed to load Telegram Web" });
    errorEl.createEl("p", { text: errorDescription || "Unknown error" });
    errorEl.createEl("p", {
      text: "Please check your internet connection and try reloading."
    });
    const reloadBtn = errorEl.createEl("button", { text: "Reload" });
    reloadBtn.addEventListener("click", () => {
      errorEl.remove();
      this.reload();
    });
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  telegramUsername: "",
  webVersion: "k",
  panelSide: "right",
  autoOpen: false
};
var TelegramSidebarSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Telegram Sidebar Settings" });
    new import_obsidian2.Setting(containerEl).setName("Telegram Username").setDesc(
      "Enter the username of the bot, user, or channel to open on launch (without @). Leave empty to show the main Telegram screen."
    ).addText(
      (text) => text.setPlaceholder("e.g. moltbot").setValue(this.plugin.settings.telegramUsername).onChange(async (value) => {
        this.plugin.settings.telegramUsername = value.trim().replace(/^@/, "");
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Telegram Web Version").setDesc("K version is lightweight. A version is React-based with modern UI.").addDropdown(
      (dropdown) => dropdown.addOption("k", "K (Lightweight)").addOption("a", "A (Modern React)").setValue(this.plugin.settings.webVersion).onChange(async (value) => {
        this.plugin.settings.webVersion = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Panel Side").setDesc("Which side of the workspace to open the Telegram panel.").addDropdown(
      (dropdown) => dropdown.addOption("right", "Right").addOption("left", "Left").setValue(this.plugin.settings.panelSide).onChange(async (value) => {
        this.plugin.settings.panelSide = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Auto Open on Startup").setDesc("Automatically open the Telegram sidebar when Obsidian starts.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoOpen).onChange(async (value) => {
        this.plugin.settings.autoOpen = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var TelegramSidebarPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_TELEGRAM, (leaf) => {
      return new TelegramView(leaf, this);
    });
    this.addCommand({
      id: "send-note-path-to-telegram",
      name: "Send Current Note Path to Telegram",
      callback: () => this.sendNotePathToTelegram()
    });
    this.addRibbonIcon("send", "Open Telegram Sidebar", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-telegram-sidebar",
      name: "Open Telegram Sidebar",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "reload-telegram",
      name: "Reload Telegram",
      callback: () => this.reloadView()
    });
    this.addCommand({
      id: "go-to-chat",
      name: "Go to Chat",
      callback: () => {
        const view = this.getActiveView();
        if (view) {
          view.navigateToChat(this.settings.telegramUsername);
        } else {
          this.activateView();
        }
      }
    });
    this.addSettingTab(new TelegramSidebarSettingTab(this.app, this));
    if (this.settings.autoOpen) {
      this.app.workspace.onLayoutReady(() => {
        this.activateView();
      });
    }
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_TELEGRAM);
  }
  async activateView() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_TELEGRAM);
    if (existing.length > 0) {
      workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.settings.panelSide === "left" ? workspace.getLeftLeaf(false) : workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({
        type: VIEW_TYPE_TELEGRAM,
        active: true
      });
      workspace.revealLeaf(leaf);
    }
  }
  getActiveView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_TELEGRAM);
    if (leaves.length > 0) {
      return leaves[0].view;
    }
    return null;
  }
  reloadView() {
    const view = this.getActiveView();
    if (view) {
      view.reload();
    }
  }
  async sendNotePathToTelegram() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile)
      return;
    const vaultBasePath = this.app.vault.adapter.basePath;
    const absolutePath = `${vaultBasePath}/${activeFile.path}`;
    const view = this.getActiveView();
    if (!view) {
      await this.activateView();
      const newView = this.getActiveView();
      if (newView) {
        setTimeout(() => newView.insertTextToChat(absolutePath), 1e3);
      }
      return;
    }
    view.insertTextToChat(absolutePath);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
